### ISSUE TITLE
Can't install the Network-Encoder

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube-Encoder-Network#7]
When installing the network encoder , clicking on install ( after providing all the information ) , it does show very quickly , installation success . After that it does close , and send me back to : /install/index.php 

I've tried doing it manually on configuration_template.php , but still no luck 
Anything that i'm missing ?

**Comment by DanielnetoDotCom** [comment]
I know it needs some improvements, try to manually create the file configuration.php,

**Comment by akhilleusuggo** [comment]
I did , but still sends me to the /install/index.php
Even deleting the /install doesn't work

**Comment by DanielnetoDotCom** [comment]
try to give permission 777 on the configuration.php file and run the installation

**Comment by akhilleusuggo** [comment]
Do you mean the configuration_template.php ?

**Comment by akhilleusuggo** [comment]
Didn't work anyway ( on the db everything is writted , but not on the config file )

**Comment by DanielnetoDotCom** [comment]
cant you manually add the configuration file based on the template?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom man , I have installed it on 3 different server and none of them works . Please take a look again on that . Maybe with the updates this one has lost the compatibility

**Comment by DanielnetoDotCom** [comment]
lets do this, email me one of those server credentials and domain I will take a look for you.
developer@youphptube.com

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I managed to make it work . I was so fool , I haven't removed the _template .
It's working fine , just one problem . The network-recommendation is not working . It does always sends to the same encoder . That encoder right now has 16 on the queue , the others 0 . On the configuration site under ''Advanced Configuration'' Encoder URL , I have that encoder , let's call it Enc4 , even removing it ( empty spot ) , still does send to the enc4 . I've cleared the cache and everything , but no luck

**Comment by DanielnetoDotCom** [comment]
the only time I saw this happen is when the network could not ping on the encoder, so it always chooses the offline encoder
