### ISSUE TITLE
small visual enhancement with CSS

### ISSUE THREAD

**Issue by maxlinux2000** [YouPHPTube/YouPHPTube-Encoder-Network#9]
Add to the end of the style.css file

/var/www/html/YouPHPTube-Encoder-Network/view/css/style.css

... this code:

```
li.active {
    border-bottom: 3px solid black;
    border-left: 1px solid black;
    border-top: 1px solid black;
}

.account-amount {
    font-family: 'Roboto', sans-serif;
    color: #656667;
    font-size: 0.8em;
    line-height: 0.8em;
}
.account-type {
    font-family: 'Roboto', sans-serif;
    color: #A0AEB6;
    font-size: 0.9em;
    font-weight: bold;
    line-height: 0.9em;
    display: block;
}
```

Result:

![Captura de pantalla de 2019-09-29 14-25-58](https://user-images.githubusercontent.com/5683921/65832516-2513cc80-e2c5-11e9-8b38-1ebb326d74e7.png)

**Comment by DanielnetoDotCom** [comment]
Thank you, please next time feel free to make a pull request.

if you do it, your name will appear as a project contributor

**Comment by maxlinux2000** [comment]
It's no so important that my name, appears. The important is that this tool works better every days for our mission in the world.
